---
- hosts: all
  gather_facts: false

  tasks:
    - name: Create VM with defaults
      delegate_to: localhost
      azure_rm_virtualmachine:
        vm_size: "{{ my_vm_size }}"
        location: "{{ my_location }}"
        resource_group: "{{ myresourcegroup }}"
        name: "{{ vm_name }}"
        admin_username: "{{ admin_username }}"
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
            key_data: "{{ ssh_pub_key }}"
        tags:
          worker: ""
        image:
          offer: RHEL
          publisher: RedHat
          sku: '8.1'
          version: latest
