---
- hosts: all

  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        resource_group: "{{ myresourcegroup }}"
        name: testvm10
        admin_username: "{{ admin_username }}"
        admin_password: "{{ ssh_pub_key }}"
        tags:
          worker:
        image:
          offer: RHEL
          publisher: RedHat
          sku: '8.1'
          version: latest
