---
- name: Deploy Apache
  hosts: all
  become: true
  tasks:
    - name: Install apache packages 
      yum:
        name: httpd
        state: present
    - name: ensure httpd is running
      service:
        name: httpd 
        state: started
    - name: make sure firewalld python package is installed
      yum:
        name: python-firewall
        state: present
    - name: Open port 80 for http access
      firewalld:
        port: 80/tcp
        state: enabled
        immediate: true
    - name: Restart the firewalld service to load in the firewall changes
      service: 
        name: firewalld 
        state: restarted
