---
- hosts: all
  gather_facts: False

  tasks:
    - name: Register and attach with an activation key
      redhat_subscription:
        state: present
        server_hostname: "{{ satellite_hostname }}"
        server_insecure: true
        activationkey: "{{ satellite_activation_key }}"
        org_id: "{{ satellite_org_id }}"
        auto_attach: true