---
- name: Uninstall IIS
  hosts: all

  tasks:
    - name: Uninstall IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server
        state: absent
      register: win_feature
   
    - name: Remove Firewall rule
      win_firewall_rule:
        name: mysite
        state: absent
        
    - name: Reboot if installing Web-Server feature requires it
      win_reboot:
      when: win_feature.reboot_required