---
# tasks file for rhel.httpd
- name: ensure httpd and firewalld are installed
  dnf:
    name:
      - httpd
      - firewalld
    state: latest

- name: ensure httpd and firewalld are enabled
  service:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - httpd
    - firewalld

- name: firewalld is configured
  firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true

- name: ensure sample index.html is installed
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd
