---
- name: Detach RHEL host
  hosts: all

  tasks:
    - name: Unregister host
      redhat_subscription:
        state: absent
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool_ids: "{{ rhn_pool_id }}"
