---
- name: Ensure SSH server is hardened
  hosts: all

  tasks:
    - name: Ensure root SSH login is disabled
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify:
        - restart sshd
    
    - name: Ensure password SSH login is disabled
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify:
        - restart sshd
    
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted